apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::739179596963:role/eksctl-simple-jwt-apii-nodegroup-NodeInstanceRole-JIN3LTPCGS9S
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::739179596963:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-09-28T06:17:15Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1270"
  uid: 3a93ace4-efc8-4440-8122-2d38a5405c20
